public with sharing class CourseController {
	
	/*
CourseImporter ci = new CourseImporter('http://aluno.impactaonline.com.br');
List<Course__c> lcc = new List<Course__c>();
lcc = ci.getCourses();

for(Course__c c: lcc) {
	System.debug('ID: ' + c.course_id__c);
	System.debug('Titulo: ' + c.title__c);
	System.debug('Descricao: ' + c.description__c);
	System.debug('Carga Horaria: ' + c.workload__c);

User[] auth_token = [SELECT Eadbox_Auth_Token__c FROM User WHERE Id = :UserInfo.getUserId()];
System.debug('Token: ' + auth_token[0].Eadbox_Auth_Token__c);
	
	*/

}